spring.profiles.active=dev

# common
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

# jwt
security.jwt.secret=mylengthysecretkeyforjwttokensP@$$W0rD
security.jwt.accessTokenExpirationMs=900000
security.jwt.refreshTokenExpirationMs=604800000

# email test
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=none
spring.mail.password=none
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
